# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = '[âžœ](bold green)'
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[docker_context]
disabled = true
